//! Message traits, placement definitions, and late-reply policy types.

use std::any::Any;

use crate::call::CallResponseMessage;
use crate::session::{Response, SessionId};
use crate::stream::{StreamEvent, StreamEventMessage};

/// Placement class for a message in the receiving task's queue.
#[derive(Debug, Clone, Copy, Eq, PartialEq, Hash)]
pub enum MessagePlacement {
    /// Default FIFO queue.
    Normal,

    /// Priority FIFO queue, received before normal messages.
    Priority,
}

/// Runtime policy for protocol replies that arrive after their session has no
/// active waiter.
#[derive(Debug, Clone, Copy, Eq, PartialEq, Hash)]
pub enum LateReplyPolicy {
    /// Pass the late reply to the receiving task's late-reply callback.
    Report,

    /// Treat the late reply as an allowed obsolete protocol message.
    Ignore,
}

/// Kind of late reply observed by a receiving task.
#[derive(Debug, Clone, Copy, Eq, PartialEq, Hash)]
pub enum LateReplyKind {
    /// Late one-shot call response.
    CallResponse,

    /// Late stream reply event.
    StreamEvent,
}

/// Action returned by a task's late-reply callback.
#[derive(Debug, Clone, Copy, Eq, PartialEq, Hash)]
pub enum LateReplyAction {
    /// Ignore the late reply and continue running the task.
    Ignore,

    /// Stop the receiving task.
    Terminate,
}

/// Borrowed view of a late reply passed to a task late-reply callback.
pub struct LateReplyRef<'a> {
    session_id: SessionId,
    kind: LateReplyKind,
    payload: &'a (dyn Any + Send),
}

impl<'a> LateReplyRef<'a> {
    /// Construct a borrowed late-reply view.
    #[must_use]
    pub const fn new(
        session_id: SessionId,
        kind: LateReplyKind,
        payload: &'a (dyn Any + Send),
    ) -> Self {
        Self {
            session_id,
            kind,
            payload,
        }
    }

    /// Return the session ID carried by the late reply.
    #[must_use]
    pub const fn session_id(&self) -> SessionId {
        self.session_id
    }

    /// Return the late reply kind.
    #[must_use]
    pub const fn kind(&self) -> LateReplyKind {
        self.kind
    }

    /// Attempt to inspect the late reply payload as a concrete type.
    #[must_use]
    pub fn downcast_ref<T: 'static>(&self) -> Option<&T> {
        self.payload.downcast_ref::<T>()
    }
}

/// Trait implemented by message enums that can be stored in a task queue.
pub trait TaskMessage: Sized + Send + 'static {
    /// Return the receiver-declared placement for this message.
    fn placement(&self) -> MessagePlacement;
}

/// Marker/conversion trait used for compile-time receive checks.
pub trait CanReceive<T>: TaskMessage {
    /// Wrap a received protocol value into the task's message enum.
    fn wrap(value: T) -> Self;
}

/// Type-erased task endpoint capable of receiving one typed message.
pub trait MessageTarget<T>: Send + Sync {
    /// Enqueue the typed message through the receiving task's generated queue.
    fn send(&self, value: T) -> Result<(), crate::error::SendError>;
}

/// Framework-only queue-space wakeup message.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct QueueSpaceWakeup;

/// Message enums that can carry framework-only queue-space wakeups.
///
/// These messages are generated by `mpi-rs` and are not declared by users in
/// protocols, task receive declarations, or handler signatures.
pub trait QueueSpaceWakeupMessage: Sized {
    /// Wrap a queue-space wakeup into this task's message enum.
    fn queue_space_wakeup() -> Self;

    /// Extract a queue-space wakeup from this message, if it is one.
    fn into_queue_space_wakeup(self) -> Result<QueueSpaceWakeup, Self>;
}

/// Protocol receive values that can be wrapped into a generated task message.
pub trait ProtocolReceive: Send + 'static {
    /// Wrap this protocol receive value into a task message.
    fn into_task_message<M>(self) -> M
    where
        M: TaskMessage + CallResponseMessage + StreamEventMessage;
}

impl<T> ProtocolReceive for Response<T>
where
    T: Send + 'static,
{
    fn into_task_message<M>(self) -> M
    where
        M: TaskMessage + CallResponseMessage + StreamEventMessage,
    {
        M::call_response(self.session_id, Box::new(self.value) as Box<dyn Any + Send>)
    }
}

impl<T, E> ProtocolReceive for StreamEvent<T, E>
where
    T: Send + 'static,
    E: Send + 'static,
{
    fn into_task_message<M>(self) -> M
    where
        M: TaskMessage + CallResponseMessage + StreamEventMessage,
    {
        let session_id = self.session_id();
        M::stream_event(session_id, Box::new(self) as Box<dyn Any + Send>)
    }
}

/// Trait for protocol messages that belong to a logical session.
pub trait HasSessionId {
    /// Return the logical interaction identifier carried by this message.
    fn session_id(&self) -> SessionId;
}
