name: Fmt Debug

on:
  pull_request:

jobs:
  fmt-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Quiet fmt check
        run: |
          git clone --quiet --depth 1 --branch "$GITHUB_HEAD_REF" "https://github.com/$GITHUB_REPOSITORY.git" .
          rustup component add rustfmt >/dev/null
          cargo fmt --all --check
